### ISSUE TITLE
Run Hurricane Matthew test case in METplus container

### ISSUE THREAD

**Issue by jaredalee** [NCAR/i-wrf#48]
## Describe the Task ##
Using the WRF output generated by #46 and the observation data obtained in #47,  generate some sample verification statistics with the METplus container. Document what commands/steps were used. This will also serve as another test to make sure that #5 is working properly.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
7790013

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Task Checklist ##
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jaredalee** [comment]
As a placeholder until the WRF output from the Hurricane Matthew test case from the container is available, the output from a standalone version of WRF for this case is here: /glade/derecho/scratch/jaredlee/nsf_i-wrf/matthew/wrf

**Comment by JohnHalleyGotway** [comment]
@georgemccabe, @jaredalee, and @JohnHalleyGotway met on April 17th for a working session.

Steps:
- Log on to casper and follow [these instructions](https://dtcenter.org/community-code/metplus/metplus-5-1-existing-builds) to load the METplus environment.
```
ssh -Y johnhg@casper.hpc.ucar.edu
```
- Run `run_metplus.py` and `grid_stat` to confirm that everything's in your path.
- `which run_metplus.py` to see where it's installed... also set as `$METPLUS_PATH`.
- Reviewed the details of the [Point-Stat basic use case](https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/PointStat/PointStat.html#sphx-glr-generated-met-tool-wrapper-pointstat-pointstat-py).
- Discussed that issue dtcenter/MET#1518 is needed to rotate the winds from grid to earth relative fop WRF NetCDF output prior to comparing to obs. Recommend that @JohnHalleyGotway should work on this for the I-WRF project.
- Run a canned [Point-Stat use case](https://metplus.readthedocs.io/en/latest/generated/met_tool_wrapper/index.html#pointstat). Here we set `config.OUTPUT_BASE` on the command line to define the output directory:
```
run_metplus.py $METPLUS_PATH/parm/use_cases/met_tool_wrapper/PointStat/PointStat.conf config.OUTPUT_BASE=/glade/derecho/scratch/johnhg/METplus_output
```
- Cat the run-specific log file for more details:
```
cat /glade/derecho/scratch/johnhg/METplus_output/logs/metplus.log.20240419161254
```
- Could also run with a user-specific METplus config file and run with:
```
run_metplus.py $METPLUS_PATH/parm/use_cases/met_tool_wrapper/PointStat/PointStat.conf /glade/u/home/mccabe/mccabe.casper.conf 
```
- Put user-specific settings last in the list to override any setting set in earlier configs.
- Note that this i-wrf work requires using a METplus 6.0.0 beta version to read the WRF output on its native grid. But that has not yet been installed on casper. 
- Get started on a new use case by copying the example into a new file:
```
cp $METPLUS_PATH/parm/use_cases/met_tool_wrapper/PointStat/PointStat.conf /glade/u/home/mccabe/PointStat_iwrf_test.conf
```
- Configure this conf file with Hurricane Matthew-specific times and settings.
- Use template tags to update the input file paths.
- Run METplus just to confirm that it's finding the WRF files in the spot we expect:
```
run_metplus.py /glade/u/home/mccabe/PointStat_iwrf_test.conf /glade/u/home/mccabe/mccabe.casper.conf
```
- This run produces error message because MET-11.1.0 does not yet support native WRF output. Need to switch to MET-12.0.0-beta4.
-

**Comment by jprestop** [comment]
@JohnHalleyGotway and @georgemccabe 
The latest METplus beta releases are now installed on Casper.  The [Existing Builds](https://dtcenter.org/community-code/metplus/metplus-6-0-existing-builds) page has been updated to reflected this installation. Please let me know if you have any questions or problems.

**Comment by jaredalee** [comment]
George & I just finished a working meeting, where we set up the METplus config file (in the commit referenced just above) to:

a) read in the WRF output file successfully
b) read in the METAR obs file successfully
c) read and calculate stats for 2-m T, 10-m U, and 10-m V as an initial test

We uncovered a bug in MET where it doesn't currently read in multiple obs files. George will create an issue and then fix that. Next time we'll add configurations to handle processing the RAOB obs file and determine if MET is properly interpolating native-grid WRF output to pressure levels, or if WRF needs to be re-run to output variables on specific pressure levels in a different file.

**Comment by georgemccabe** [comment]
These notes expand on the previous comment and should be added to the new issue when it is created:

There is already a METplus wrapper for the GFDLTracker. I created a Docker image on DockerHub that contains the tracker that is used to run it for the METplus automated tests.

https://github.com/dtcenter/METplus/blob/develop/.github/actions/run_tests/Dockerfile.run_gfdl

This Dockerfile could be copied and modified to create a Docker container that includes METplus and the tracker.

The image created includes patches so it can be compiled using GCC instead of Intel. We could instead compile it using Intel since we already compile WRF using Intel. Here is the Dockerfile that builds the tracker using GCC:
https://github.com/dtcenter/METplus/blob/develop/internal/scripts/docker_env/Dockerfile.gfdl-tracker

**Comment by JohnHalleyGotway** [comment]
Here's a list of recommended improvements to MET/METplus:

1. In MET Point-Stat, we're requesting only VL1L2, not VCNT, but are getting a warning about computing wind direction stats for 0-vectors:
```
WARNING: VL1L2Info::compute_stats() -> Skipping 85 of 459 vector pairs for which the direction difference is undefined.
WARNING: Set the "wind_thresh" and "wind_logic" configuration options to exclude zero vectors.
```
Only warn about this when VCNT output is requested.

2. In METplus PointStat wrapper, add support for setting wind_thresh and wind_logic that we used for this use case but are not currently supported by the wrapper. When this is added, you can replace the following override settings:
```
POINT_STAT_MET_CONFIG_OVERRIDES = wind_thresh   = [ >2 ]; wind_logic = INTERSECTION;
```

3. dtcenter/METplus#2567 to fix the Point-Stat wrapper bug for multiple observation files.

4. dtcenter/METplus#1514 to create a MADIS2NC wrapper.

**Comment by georgemccabe** [comment]
I was able to get a successful METplus run using apptainer on casper.

To load apptainer and pull the METplus image:
```
module load apptainer

cd ${SCRATCH}
apptainer pull docker://dtcenter/metplus:6.0.0-beta4
```

This creates a local file called `metplus_6.0.0-beta4.sif`.

Create local output directory:
```
mkdir ${SCRATCH}/metplus_out
```

Set environment variable to bind directories to container (note: this can also be accomplished by passing the value on the command line using the `--bind` argument)
* Input data directories for WRF, raob, and metar input data
   * **WRF**: /glade/derecho/scratch/jaredlee/nsf_i-wrf/matthew to /data/input/wrf 
   * **raob**: /glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/raob/netcdf to /data/input/obs/raob
   * **metar**: /glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/metar/netcdf to /data/input/obs/metar
* Config directory containing METplus use case configuration file
   *  /glade/u/home/mccabe/i-wrf/use_cases/Hurricane_Matthew/METplus to /config
* Output directory to write output
   * ${SCRATCH}/metplus_out to /data/output

```
export APPTAINER_BIND="/glade/derecho/scratch/jaredlee/nsf_i-wrf/matthew:/data/input/wrf,/glade/u/home/mccabe/i-wrf/use_cases/Hurricane_Matthew/METplus:/config,/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/raob/netcdf:/data/input/obs/raob,/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/metar/netcdf:/data/input/obs/metar,${SCRATCH}/metplus_out:/data/output"
```

Execute the run_metplus.py command inside the container to run the use case:
```
apptainer exec metplus_6.0.0-beta4.sif /metplus/METplus/ush/run_metplus.py /config/PointStat_matthew.conf
```

Check that the output data was created locally:
```
ls ${SCRATCH}/metplus_out/point_stat -1
```

> point_stat_surface_360000L_20161007_120000V_cnt.txt
> point_stat_surface_360000L_20161007_120000V.stat
> point_stat_surface_360000L_20161007_120000V_vcnt.txt
> point_stat_upper_air_360000L_20161007_120000V_cnt.txt
> point_stat_upper_air_360000L_20161007_120000V.stat
> point_stat_upper_air_360000L_20161007_120000V_vcnt.txt

If you need to run on casper outside of apptainer, you can override the input directory values with the actual paths on casper:
```
run_metplus.py \
/glade/u/home/mccabe/i-wrf/use_cases/Hurricane_Matthew/METplus/PointStat_matthew.conf \
config.FCST_POINT_STAT_INPUT_DIR=/glade/derecho/scratch/jaredlee/nsf_i-wrf/matthew \
surface.OBS_POINT_STAT_INPUT_DIR=/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/metar/netcdf \
upper_air.OBS_POINT_STAT_INPUT_DIR=/glade/campaign/ral/wsap/i-wrf/data/hurr-matthew/madis/point/raob/netcdf \
config.OUTPUT_BASE=${SCRATCH}/metplus_out2
```

**Comment by georgemccabe** [comment]
I was able to create a Docker "artifact" that can be pulled and mounted using apptainer. This is what I had to do on casper to create it:

```
module load apptainer
```

To create volume (directory obs existed in current directory that contained observation data):
```
mksquashfs obs/ input_obs.squashfs
apptainer sif new input_obs.sif
apptainer sif add --datatype 4 --partarch 2 --partfs 1 --parttype 3 input_obs.sif input_obs.squashfs
```

To push volume sif (artifact) to DockerHub:
```
apptainer remote login --username georgemccabe oras://registry-1.docker.io
# enter authentication token
apptainer push -U input_obs.sif oras://registry-1.docker.io/ncar/iwrf:data-matthew-input-obs
```

Then to run I had to pull the artifact using oras, then bind it to container:

```
cd ${SCRATCH}
mkdir metplus_out

apptainer pull docker://dtcenter/metplus:feature_1514_madis2nc-pull_request

apptainer pull data-matthew-input-obs.sif oras://registry-1.docker.io/ncar/iwrf:data-matthew-input-obs

LOCAL_METPLUS_CONFIG_DIR=/glade/u/home/mccabe/i-wrf/use_cases/Hurricane_Matthew/METplus
LOCAL_FCST_INPUT_DIR=/glade/derecho/scratch/jaredlee/nsf_i-wrf/matthew
LOCAL_OUTPUT_DIR=${SCRATCH}/metplus_out

export APPTAINER_BIND="${LOCAL_METPLUS_CONFIG_DIR}:/config,${LOCAL_FCST_INPUT_DIR}:/data/input/wrf,${LOCAL_OUTPUT_DIR}:/data/output,data-matthew-input-obs.sif:/data/input/obs:image-src=/"

apptainer exec /glade/derecho/scratch/mccabe/metplus-dev_feature_1514_madis2nc-pull_request.sif /metplus/METplus/ush/run_metplus.py /config/PointStat_matthew.conf
```
